---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: login-form
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.proxy.auth.FormLoginAuthMech
  uri: "/auth/formlogin"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: jit
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.provisioning.auth.JITAuthMech
  uri: "/auth/jit"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: genoidctoken
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.proxy.auth.GenerateOIDCTokens
  uri: "/auth/oidctoken"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: login-service
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.proxy.auth.LoginService
  uri: "/auth/loginservice"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: oidc
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.unison.proxy.auth.openidconnect.OpenIDConnectAuthMech
  uri: "/auth/oidc"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: saml2
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.proxy.auth.SAML2Auth
  uri: "/auth/saml2"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: oauth2jwt
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.proxy.auth.oauth2.OAuth2JWT
  uri: "/auth/oauth2jwt"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: oauth2k8s
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.proxy.auth.OAuth2K8sServiceAccount
  uri: "/auth/oauth2k8s"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: map
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.proxy.auth.FullMappingAuthMech
  uri: "/auth/map"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: github
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.unison.proxy.auth.github.GithubAuthMech
  uri: "/auth/github"
  init: {}
  secretParams: []
---
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationMechanism
metadata:
  name: az
  namespace: {{ .Release.Namespace }}
spec:
  className: com.tremolosecurity.proxy.auth.AuthorizationAuthMech
  uri: "/auth/az"
  init: {}
  secretParams: []

