{{ if .Values.enable_impersonation }}
---
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace }}
spec:
  azTimeoutMillis: 3000
  isApp: true
  urls:
  - hosts:
    - "#[K8S_API_HOST]"
    filterChain: 
    - className: com.tremolosecurity.proxy.filters.K8sInjectImpersonation
      params:
        targetName: k8s
        userNameAttribute: sub
        useLdapGroups: "false"
        groupAttribute: groups
    uri: "/"
    proxyTo: "${k8s_url}${fullURI}"
    authChain: oauth2jwt
    azRules:
    - scope: dn
      constraint: "o=Tremolo"
  cookieConfig:
    sessionCookieName: k8s-api-name
    domain: "#[K8S_API_HOST]"
    secure: true
    httpOnly: true
    logoutURI: "/logout"
    keyAlias: session-unison
    timeout: {{ .Values.network.session_inactivity_timeout_seconds }}
    scope: -1
    cookiesEnabled: false
{{ end }}