---
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  name: k8s-login-cli-redirect
  namespace: {{ .Release.Namespace }}
spec:
  azTimeoutMillis: 3000
  isApp: true
  urls:
  - hosts:
    - "#[OU_HOST]"
    filterChain:
    - className: com.tremolosecurity.prelude.filters.StopProcessing
      params: {}
    uri: "/cli-login"
    authChain: login-service
    regex: true
    azRules:
    - scope: dn
      constraint: "o=Tremolo"
    results:
      azSuccess: redirect-to-local-login
  cookieConfig:
    sessionCookieName: tremolosession
    domain: "#[OU_HOST]"
    secure: true
    httpOnly: true
    logoutURI: "/logout"
    keyAlias: session-unison
    timeout: {{ .Values.network.session_inactivity_timeout_seconds }}
    scope: -1
    cookiesEnabled: true
    