---
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  name: k8s-login-cli
  namespace: {{ .Release.Namespace }}
spec:
  azTimeoutMillis: 3000
  isApp: false
  urls:
  - hosts:
    - "#[OU_HOST]"
    - "127.0.0.1"
    filterChain: []
    uri: "/auth/idp/k8s-login-cli"
    azRules:
    - scope: dn
      constraint: "o=Tremolo"
    idp:
      className: com.tremolosecurity.idp.providers.OpenIDConnectIdP
      params:
        jwtSigningKey: "unison-saml2-rp-sig"
        sessionStoreClassName: "com.tremolosecurity.idp.providers.oidc.none.NoneBackend"
      mappings:
        strict: true
        map:
        - targetAttributeName: sub
          targetAttributeSource: sub
          sourceType: user
        - targetAttributeName: name
          targetAttributeSource: ${giveName} ${sn}
          sourceType: composite
        - targetAttributeName: preferred_username
          targetAttributeSource: uid
          sourceType: user
        - targetAttributeName: email
          targetAttributeSource: mail
          sourceType: user
        - targetAttributeName: groups
          targetAttributeSource: groups
          sourceType: user
      trusts:
      - name: "http://127.0.0.1:8400"
        params:
          clientID: "cli-local"
          clientSecret: ""
          publicEndpoint: "true"
          redirectURI: "http://127.0.0.1:8400/redirect"
          codeLastMileKeyName: "lastmile-oidc"
          authChainName: "login-service"
          codeTokenSkewMilis: "60000"
          accessTokenTimeToLive: "60000"
          accessTokenSkewMillis: "120000"
  cookieConfig:
    sessionCookieName: tremolosession
    domain: "#[OU_HOST]"
    secure: true
    httpOnly: true
    logoutURI: "/logout"
    keyAlias: session-unison
    timeout: {{ .Values.network.session_inactivity_timeout_seconds }}
    scope: -1
    cookiesEnabled: true