apiVersion: v1
kind: ServiceAccount
metadata:
  name: ouhtml-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ouhtml-{{ .Release.Name }}
  name: ouhtml-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.openunison.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ouhtml-{{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ouhtml-{{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.openunison.html.image }}
        imagePullPolicy: Always
        name: ouhtml
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /nginx-health
            port: 8080
            httpHeaders: []
          initialDelaySeconds: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /nginx-health
            port: 8080
            httpHeaders: []
          initialDelaySeconds: 3
          periodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: ouhtml-{{ .Release.Name }}
      automountServiceAccountToken: false
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ouhtml-{{ .Release.Name }}
  name: ouhtml-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: ouhtml-{{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP