{{ if not .Values.enable_provisioning }}
---
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: local-deployment
  namespace: {{ .Release.Namespace }}
spec:
  label: "#[K8S_DEPLOYMENT_NAME:Local Deployment]"
  azRules:
  - constraint: o=Tremolo
    scope: dn
  description: "#[K8S_DEPLOYMENT_DESC:Current Cluster]"
  parent: B158BD40-0C1B-11E3-8FFD-0800200C9A66
  showInPortal: true
  showInReports: false
  showInRequestAccess: false
  uuid: b1bf4c92-7220-4ad2-91af-ee0fe0af7312
{{ end }}