name: Build OpenUnison

on:
  push:
    branches:
      - 'main'
permissions:
  id-token: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Cosign
      uses: sigstore/cosign-installer@main
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: actions/checkout@v1
  


    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: deploy with jib
      
      run: mvn compile jib:dockerBuild --file pom.xml -Djib.httpTimeout=600000 -Dimage=local/openunison-k8s
