---
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  name: completelogin
  namespace: {{ .Release.Namespace }}
spec:
  azTimeoutMillis: 3000
  isApp: true
  urls:
  - hosts:
    - "#[OU_HOST]"
    filterChain: 
    - className: com.tremolosecurity.prelude.filters.CompleteLogin
      params: {}
    uri: "/login/auth"
    authChain: enterprise-idp
    azRules:
    - scope: dn
      constraint: "o=Tremolo"
  cookieConfig:
    sessionCookieName: tremolosession
    domain: "#[OU_HOST]"
    secure: true
    httpOnly: true
    logoutURI: "/logout"
    keyAlias: session-unison
    timeout: {{ .Values.network.session_inactivity_timeout_seconds }}
    scope: -1
    cookiesEnabled: true
    