{{ if not .Values.enable_provisioning }}
---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: jitdb
  namespace: {{ .Release.Namespace }}
spec:
  description: JIT
  inList: false
  label: JIT
  orgId: 687da09f-8ec1-48ac-b035-f2f182b9bd1e
  dynamicConfiguration:
    dynamic: false
    className: ""
    params: []
  tasks: |-
           - taskType: customTask
             className: com.tremolosecurity.provisioning.customTasks.Attribute2Groups
             params:
               attributeName: memberOf
           - taskType: mapping
             strict: true
             map:
             - targetAttributeName: TREMOLO_USER_ID
               sourceType: user
               targetAttributeSource: uid
             - targetAttributeName: sub
               sourceType: user
               targetAttributeSource: uid
             - targetAttributeName: email
               sourceType: custom
               targetAttributeSource: com.tremolosecurity.mapping.DefaultEmail
             - targetAttributeName: first_name
               sourceType: static
               targetAttributeSource: na
             - targetAttributeName: last_name
               sourceType: static
               targetAttributeSource: na
             - targetAttributeName: uid
               sourceType: user
               targetAttributeSource: uid
             onSuccess:
               - taskType: provision
                 sync: true
                 target: jitdb
                 setPassword: false
                 onlyPassedInAttributes: true
                 attributes:
                 - sub
                 - email
                 - first_name
                 - last_name
                 - uid
               - taskType: resync
                 keepExternalAttrs: false
                 changeRoot: true
                 newRoot: o=Tremolo
{{ end }}